apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  labels:
    app: node
spec:
  containers:
  - name: node
    image: node:20-alpine
    command: ["node"]
    args:
      - -e
      - |
        const http = require('http');
        const server = http.createServer((req, res) => {
          res.end('Hello from Node.js Pod');
        });
        server.listen(3000);
    ports:
    - containerPort: 3000
