apiVersion: v1
kind: Pod
metadata:
  name: ruby-pod
  labels:
    app: ruby
spec:
  containers:
  - name: ruby
    image: ruby:3.3-alpine
    command: ["sh", "-c"]
    args:
      - |
        gem install webrick --no-document && \
        ruby -e "
        require 'webrick'
        server = WEBrick::HTTPServer.new(:Port => 4567)
        trap('INT') { server.shutdown }
        server.start
        "
    ports:
    - containerPort: 4567
