apiVersion: v1
kind: Pod
metadata:
  name: dotnet-pod
  labels:
    app: dotnet
spec:
  containers:
  - name: dotnet
    image: mcr.microsoft.com/dotnet/sdk:8.0
    command: ["sh", "-c"]
    args:
      - |
        dotnet new console -n HelloApp && \
        cd HelloApp && \
        dotnet run
