apiVersion: v1
kind: Pod
metadata:
 name: python-pod
 labels:
   app: python
spec:
  containers:
  - name: python
    image: python:3.12-slim
    command: ["python"]
    args: ["-m", "http.server", "8000"]
    ports:
    - containerPort: 8000