apiVersion: v1
kind: Pod
metadata:
  name: logging-sidecar-pod
spec:
  volumes:
  - name: log-volume
    emptyDir: {}

  containers:
  - name: app
    image: busybox
    command: ["sh", "-c"]
    args:
      - |
        while true; do
          echo "$(date) App log entry" >> /var/log/app.log
          sleep 5
        done
    volumeMounts:
    - name: log-volume
      mountPath: /var/log

  - name: log-sidecar
    image: busybox
    command: ["sh", "-c"]
    args:
      - |
        tail -f /var/log/app.log
    volumeMounts:
    - name: log-volume
      mountPath: /var/log
